[project]
name = "colrev.general_polish"
description = "CoLRev package for general_polish"
version = "0.1.0"
license = "MIT"
authors = [
    "Gerit Wagner <gerit.wagner@uni-bamberg.de>"
]
requires-python = ">=3.8, <4"
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/general_polish"

[tool.colrev]
colrev_doc_description = "General Polish"
colrev_doc_link = "README.md"
search_types = []

[project.entry-points."colrev"]
prep = "colrev.packages.general_polish.src.general_polish:GeneralPolishPrep"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
