[project]
name = "colrev.screen_table"
description = "CoLRev package for screen_table"
version = "0.1.0"
license = {text = "MIT"}
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
 ]
requires-python = ">=3.8, <4"

[project.urls]
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/screen_table"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.colrev]
colrev_doc_description = "Screen Table"
colrev_doc_link = "README.md"
search_types = []

[project.entry-points.colrev]
screen = "colrev.packages.screen_table.src.screen_table:TableScreen"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
