default_language_version:
    python: python3
repos:
-   repo: https://github.com/geritwagner/colrev-hooks
    rev: 22fce71d34747b2aa6c323c842382a4364938bb9
    hooks:
    -   id: format
        name: "CoLRev ReviewManager: format"
        entry: colrev_hooks/format.py
        language: script
        files: 'records.bib|paper.md|settings.json'
    -   id: check
        name: "CoLRev ReviewManager: checks"
        entry: colrev_hooks/check.py
        language: script
        files: 'records.bib|paper.md'
    -   id: report
        name: "CoLRev ReviewManager: report"
        entry: colrev_hooks/report.py
        language: script
        stages: [prepare-commit-msg]
    -   id: sharing
        name: "CoLRev ReviewManager: sharing"
        entry: colrev_hooks/sharing.py
        language: script
        stages: [push]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
