[project]
name = "colrev.scoping_review"
description = "CoLRev package for scoping_review"
version = "0.1.0"
license = "MIT"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
 ]
requires-python = ">=3.8, <4"
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/scoping_review"

[[tool.poetry.packages]]
include = "src"

[tool.colrev]
colrev_doc_description = "Scoping Review"
colrev_doc_link = "README.md"
search_types = []

[project.entry-points."colrev"]
review_type = "colrev.packages.scoping_review.src.scoping_review:ScopingReview"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
