default_language_version:
    python: python3
repos:
-   repo: https://github.com/geritwagner/colrev-hooks
    rev: 3bb16ccb207ef5a13cb261c037e7b20fede4c4c0
    hooks:
    -   id: format
        name: "ReviewManager: format"
        entry: colrev_hooks/format.py
        language: script
        files: 'references.bib|paper.md|settings.json'
    -   id: check
        name: "ReviewManager: checks"
        entry: colrev_hooks/check.py
        language: script
        files: 'references.bib|paper.md'
    -   id: report
        name: "ReviewManager: report"
        entry: colrev_hooks/report.py
        language: script
        stages: [prepare-commit-msg]
    -   id: sharing
        name: "ReviewManager: sharing"
        entry: colrev_hooks/sharing.py
        language: script
        stages: [push]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-yaml
