[project]
name = "colrev.doi_org"
description = "CoLRev package for doi_org"
version = "0.1.0"
license = {text = "MIT"}
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
 ]
requires-python = ">=3.8, <4"

[project.urls]
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/doi_org"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.colrev]
colrev_doc_description = "Doi.org"
colrev_doc_link = "README.md"
search_types = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
