[tool.poetry]
name = "colrev.genai"
description = "CoLRev package for GenAI"
version = "0.1.0"
authors = ["Julian Prester <julian.prester@sydney.edu.au>", "Gerit Wagner <gerit.wagner@uni-bamberg.de>"]
documentation = "README.md"

[[tool.poetry.packages]]
include = "src"

[tool.poetry.dependencies]
python = ">=3.8, <4"
instructor = "^1.2.6"
litellm = "^1.37.0"
pydantic = "^2.7.1"

[tool.colrev]
dev_status = "experimental"
prescreen = "colrev.packages.genai.src.genai_prescreen:GenAIPrescreen"
screen = "colrev.packages.genai.src.genai_screen:GenAIScreen"

[build-system]
requires = ["poetry-core>=1.0.0", "cython<3.0"]
build-backend = "poetry.core.masonry.api"